 #!/usr/bin/env python

import sys
import glob
import argparse

parser = argparse.ArgumentParser(description='''This script will take the files generated by estimate-gene-coverage-from-hmms-and-covstats.py for the scaffolds of a single sample and put together a file that contains the coverage observed for each of the scaffolds across all samples. ''')
parser.add_argument('--gene', help='the name of gene that you want to calculate total coverage in each sample')
parser.add_argument('--path', help='the full path to the files containing the coverage information')
parser.add_argument('--sample', help='the name of the sample that you are exploring.')
parser.add_argument('--out',help='the file to write incredible results')
args = parser.parse_args()

outfile = open(args.out, 'w')
outfile.write('sample'+'\t'+args.gene+'\t'+args.gene+'_source'+'\t'+args.gene+'_source_depth'+'\t'+args.gene+'_comparison'+'\t'+args.gene+'_comparison_depth'+'\n')
paths = args.path+args.sample+"*"+args.gene+".txt"
#print(paths)
for cov_file in glob.glob(paths):
    with open(cov_file, 'r') as f:
        sums = []
        for line in f:
            x = line.strip().split('\t')
            if x[0]=='scaffold':
                sample_name = x[1].split('/')[1]
                source = x[1].split('/')[1].split('-')[0]+'_'+x[1].split('/')[1].split('-')[1]
                source_depth = x[1].split('/')[1].split('-')[1]
                comparison = x[1].split('/')[1].split('-')[3]+'_'+x[1].split('/')[1].split('-')[4]
                comparison_depth = x[1].split('/')[1].split('-')[4]
                outfile.write(sample_name+'\t'+source+'\t'+source_depth+'\t'+comparison+'\t'+comparison_depth+'\t')
                
            else:
               sums.append(round(float(x[1]),4))
        outfile.write(str(sum(sums))+'\n')
